name: bee_five
description: "Bee Five game app."
publish_to: 'none'

version: 1.0.0+8

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  audioplayers: ^6.1.0
  supabase_flutter: ^2.8.4
  flutter_dotenv: ^5.2.1
  provider: ^6.1.2
  app_links: ^6.3.2
  google_mobile_ads: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/BEE-FIVE.png
    - assets/mapImagery/
    - assets/homeImagery/
    - assets/socials/
    - assets/sounds/
