// Dimension constants for consistent sizing
export const DIMENSIONS = {
  // Header
  HEADER_HEIGHT: 80,
  HEADER_TOP_MARGIN: 20,
  HEADER_PADDING_HORIZONTAL: 15,
  HEADER_PADDING_TOP: 10,
  
  // Logo
  LOGO_HEIGHT: 35,
  LOGO_WIDTH: 120,
  LOGO_MAX_WIDTH: 140,
  
  // Profile
  PROFILE_BUTTON_SIZE: 45,
  PROFILE_ICON_SIZE: 24,
  
  // Bees
  BEE_LARGE_SIZE: 60,
  BEE_SMALL_SIZE: 30,
  BEE_LARGE_EMOJI: 50,
  BEE_SMALL_EMOJI: 25,
  BEE_OFFSET: 30,
  BEE_SMALL_OFFSET: 15,
  
  // Buttons
  BUTTON_MIN_WIDTH: 250,
  BUTTON_PADDING_VERTICAL: 16,
  BUTTON_PADDING_HORIZONTAL: 32,
  BUTTON_BORDER_WIDTH: 3,
  BUTTON_EMOJI_SIZE: 24,
  BUTTON_TEXT_SIZE: 18,
  
  // Title
  TITLE_SIZE: 64,
  SUBTITLE_SIZE: 18,
  CONNECT_FIVE_SIZE: 20,
  
  // Footer
  FOOTER_TEXT_SIZE: 12,
  
  // Staircase
  STEP_WIDTH: 8,
  STEP_HEIGHTS: [6, 10, 14, 18, 22],
  ARROW_SIZE: 18,
  LEVEL_NUMBER_SIZE: 18,
};

